### ISSUE TITLE
Don't upgrade when the version is already installed

### ISSUE THREAD

**Issue by cbandy** [sous-chefs/rvm#146]
When using an `upgrade_strategy` with a specific version, it's possible to skip the upgrade if the requested version is already installed.

I'm not sure where such behavior should go, but I am able to test the rvm version with this command:

``` shell
rvm version | grep -q '^rvm 1.16.20'
```

So perhaps something like this in `upgrade_rvm`?

``` ruby
upgrade_check = rvm_wrap_cmd(
  %{rvm version | grep -q '^rvm #{opts[:upgrade_strategy]}'}, user_dir
)
```

**Comment by cmluciano** [comment]
@cgriego Can you please submit this PR here?
