### ISSUE TITLE
Cannot install on ubuntu/trusty64 vagrant box

### ISSUE THREAD

**Issue by SanderMander** [sous-chefs/rvm#279]
==> default: GPG signature verification failed for '/usr/local/rvm/archives/rvm-1.26.0.tgz' - 'https://github.com/wayneeseguin/rvm/releases/download/1.26.0/1.26.0.tar.gz.asc'!
==> default: try downloading the signatures:
==> default:
==> default:     gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3
==> default:
==> default: they can be compared with:
==> default:
==> default:     https://rvm.io/mpapis.asc
==> default:     https://keybase.io/mpapis
==> default: STDERR: gpg: Signature made Wed Oct 29 12:52:06 2014 UTC using RSA key ID BF04FF17
==> default: gpg: Can't check signature: public key not found
==> default: gpg: Signature made Wed Oct 29 12:52:06 2014 UTC using RSA key ID BF04FF17
==> default: gpg: Can't check signature: public key not found
==> default: ---- End output of bash /var/chef/cache/rvm-installer-root stable ----
==> default: Ran bash /var/chef/cache/rvm-installer-root stable returned 2
==> default: [2014-10-31T06:51:36+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by neurogenesis** [comment]
GPG signature checks are pointless if you're executing bash scripts as a privileged user off of a public site. If the rvm site were to get hacked then arbitrary bash script would be run as root (default for chef anyway). The chef community should discourage the use of blind ```curl ... | bash``` in favor of package management or checksum validation of downloaded scripts.
