### ISSUE TITLE
Use --no-document instead of --no-rdoc --no-ri

### ISSUE THREAD

**Issue by sethfreeman** [sous-chefs/rvm#374]
# Brief Description

Change "--no-rdoc --no-ri" to "--no-document"

## Cookbook version

0.9.4

## Chef-client version

12.17.44

## Platform Details

Ubuntu 14.04 

## Scenario

I'm trying to run chef-client to install a new ruby in rvm, but getting this error:

## Steps to Reproduce

Run chef client with rvm cookbook.

## Expected Result

Expecting ruby to be installed.

## Actual Result

Ruby is not installed because --rdoc --ri is deprecated in favor of --nodocument.

There is an attribute for rvm_gem_options which I have overridden, but it is not used by the resource attempting to install the ruby.

    rvm_gem[bundler] (/var/chef/cache/cookbooks/rvm/providers/global_gem.rb line 48) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of bash -c "source /etc/profile.d/rvm.sh && rvm ruby-2.6.3@global do gem install bundler -q --no-rdoc --no-ri -v \"1.17.3\"" ----
    STDOUT: 
    STDERR: ERROR:  While executing gem ... (OptionParser::InvalidOption)
        invalid option: --no-rdoc
    ---- End output of bash -c "source /etc/profile.d/rvm.sh && rvm ruby-2.6.3@global do gem install bundler -q --no-rdoc --no-ri -v \"1.17.3\"" ----
    Ran bash -c "source /etc/profile.d/rvm.sh && rvm ruby-2.6.3@global do gem install bundler -q --no-rdoc --no-ri -v \"1.17.3\"" returned 1
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/rvm/libraries/rvm_rubygems_package.rb:160:in `install_via_gem_command'
    /var/chef/cache/cookbooks/rvm/libraries/rvm_rubygems_package.rb:135:in `install_package'
    /var/chef/cache/cookbooks/rvm/providers/global_gem.rb:57:in `gem_package_wrapper'
    /var/chef/cache/cookbooks/rvm/providers/global_gem.rb:35:in `block (3 levels) in class_from_file'
    /var/chef/cache/cookbooks/rvm/providers/global_gem.rb:34:in `each'
    /var/chef/cache/cookbooks/rvm/providers/global_gem.rb:34:in `block (2 levels) in class_from_file'

**Comment by damacus** [comment]
Hey, 

thanks for opening an issue for this, can you open a quick PR and I'll merge it super quick!

**Comment by sethfreeman** [comment]
I’d be glad to. Thanks!

**Comment by djordje-petrovic** [comment]
So what happened with this one? Having the same issue.

**Comment by damacus** [comment]
We're still waiting for a PR.

Sorry for not responding to this sooner, it got buried under github notifications

**Comment by kirillshevch** [comment]
Having the same issue

**Comment by damacus** [comment]
Locking this thread in hope someone want s to open a PR to resolve this 👍
